# Generated by Django 3.2.13 on 2023-09-20 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_message_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message')),
                ('users', models.ManyToManyField(related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.ManyToManyField(related_name='message_reactions', to='message.Reaction'),
        ),
    ]
