# Generated by Django 3.2.13 on 2023-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_server_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
