# Generated by Django 3.2.13 on 2023-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('server', '0003_alter_server_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='channels',
            field=models.ManyToManyField(related_name='channels', to='channel.Channel'),
        ),
    ]
