# Generated by Django 3.2.13 on 2023-09-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_server_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
