# Generated by Django 3.2.13 on 2023-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('name', models.CharField(max_length=12)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
