# Generated by Django 3.2.13 on 2023-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='message.Message'),
        ),
    ]
