# Generated by Django 3.2.13 on 2023-07-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='admin_perm_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='admin_perm_edit_perms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='admin_perm_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='default_perm_write',
            field=models.BooleanField(default=True),
        ),
    ]
