# Generated by Django 3.2.13 on 2023-07-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20230719_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='admin_perm_edit',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='admin_perm_edit_perms',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='admin_perm_write',
        ),
        migrations.AddField(
            model_name='channel',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
