# Generated by Django 3.2.13 on 2023-09-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_channel_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='edited',
        ),
    ]
