# Generated by Django 3.2.13 on 2023-07-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
        ('user', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='servers',
            field=models.ManyToManyField(to='server.Server'),
        ),
    ]
