# Generated by Django 3.2.13 on 2023-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
        ('user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dms',
            field=models.ManyToManyField(to='dm.DM'),
        ),
    ]
