# Generated by Django 3.2.13 on 2023-07-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_dms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dms',
        ),
    ]
