# Generated by Django 3.2.13 on 2023-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0002_auto_20230725_1307'),
        ('user', '0007_remove_user_dms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dms',
            field=models.ManyToManyField(to='dm.DM'),
        ),
    ]
